### PR TITLE
Some ux improvements in the python tutorial

### PR DESCRIPTION
**Pull request by romeo1m**
- remove trailing spaces as they add a horizontal scrollbar without being necessary
- enable line numbers for code snippets from theme
- add some admonitions to catch user's attention
- add permalinks for headings for easier references

### CODE REVIEW

**Comment by romeo1m** [comment]
I agree that no-python code would look better without line numbers. However, the big plus in not hardcoding line numbers is that the user can copy only the code and paste it without being forced to remove each line number. I'm looking make the other blocks to be excepted from line numbering. That would ideal from my pov.

**Comment by mvnm** [comment]
Sounds good!

**Comment by romeo1m** [comment]
Plus, by hardcoding the line numbers, that python code is not highlighted.

**Comment by romeo1m** [comment]
bad luck :disappointed:  https://stackoverflow.com/questions/55653184/enable-line-numbers-for-specific-markdown-code-listings-designated-with-backtick

**Comment by romeo1m** [comment]
I worked around it with <pre> tag. Looks good to me.

**Pull request merged**
